version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    container_name: my_postgres_container2
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_postgres_data: